{{- if and (not .Values.auth.existingSecret) .Values.auth.pushAuthToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-ci-metrics-exporter.fullname" . }}
  labels:
    {{- include "gitlab-ci-metrics-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  PUSH_AUTH_TOKEN: {{ .Values.auth.pushAuthToken | quote }}
{{- end }}
